USE `cms_framework`;

-- Seed Akun Admin & Editor (Password: admin123 & editor123)
-- Hash generated by password_hash('admin123', PASSWORD_BCRYPT)
INSERT INTO `users` (`id`, `username`, `name`, `email`, `password`, `role`) VALUES
(1, 'admin', 'Administrator Utama', 'admin@cms.local', '$2y$10$tZz2Y7l9QjD9aY3sVlWgeOCp6U3hGzXoR4p7vH1y1pW8m9qK1e4yG', 'admin'),
(2, 'editor', 'Redaksi Konten', 'editor@cms.local', '$2y$10$tZz2Y7l9QjD9aY3sVlWgeOCp6U3hGzXoR4p7vH1y1pW8m9qK1e4yG', 'editor')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);

-- Seed Kategori
INSERT INTO `categories` (`id`, `name`, `slug`, `description`) VALUES
(1, 'Teknologi', 'teknologi', 'Artikel dan berita seputar perkembangan dunia teknologi dan pemrograman.'),
(2, 'Tutorial', 'tutorial', 'Panduan teknis langkah demi langkah untuk developer.'),
(3, 'Pengumuman', 'pengumuman', 'Informasi dan pembaruan seputar situs web.')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`);

-- Seed Artikel Sampel
INSERT INTO `posts` (`id`, `user_id`, `category_id`, `title`, `slug`, `excerpt`, `content`, `status`, `views`) VALUES
(1, 1, 1, 'Selamat Datang di Framework CMS PHP MVC', 'selamat-datang-di-framework-cms-php-mvc', 'Framework baru yang ringan, zero-dependency, dan didesain khusus untuk performa tinggi.', '<p>Selamat datang di kerangka <strong>Framework CMS PHP MVC</strong> baru Anda!</p><p>Framework ini dibangun murni menggunakan PHP native tanpa dependensi eksternal dari Composer. Seluruh core engine mulai dari Autoloader, Router berkonvensi, Base Model PDO, View Engine dengan Master Layout, hingga Custom CSS Library dibuat secara modular dan terstruktur rapi.</p><p>Anda dapat mengelola artikel ini melalui panel admin di menu <em>Posts</em>.</p>', 'published', 15),
(2, 1, 2, 'Panduan Mengakses Standalone REST API (api-info)', 'panduan-mengakses-standalone-rest-api-api-info', 'Pelajari cara mengonsumsi endpoint data JSON melalui aplikasi terpisah api-info.', '<p>Aplikasi REST API diletakkan terpisah pada folder <code>api-info/</code> di dalam proyek ini.</p><p>Dengan konfigurasi database mandiri dan arsitektur token authentication, Anda dapat menghubungkan aplikasi mobile, frontend SPA (React/Vue), atau pihak ketiga tanpa mengganggu sistem CMS web utama.</p>', 'published', 8)
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`);

-- Seed Pengaturan Situs
INSERT INTO `settings` (`id`, `setting_key`, `setting_value`) VALUES
(1, 'site_title', 'Modern PHP MVC CMS'),
(2, 'site_tagline', 'Framework Ringan, Cepat, dan Mandiri'),
(3, 'admin_email', 'admin@cms.local'),
(4, 'footer_text', '© 2026 Modern PHP MVC CMS. Hak Cipta Dilindungi.'),
(5, 'posts_per_page', '10'),
(6, 'site_logo', '')
ON DUPLICATE KEY UPDATE `setting_value`=VALUES(`setting_value`);

-- Seed Token API Default untuk Pengujian REST API
INSERT INTO `api_tokens` (`id`, `user_id`, `token`, `name`) VALUES
(1, 1, 'test-token-cms-info-2026', 'Master Testing Token')
ON DUPLICATE KEY UPDATE `token`=VALUES(`token`);
